version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "changeme"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
