version: "3.7"

services:

  backend:
    image: dotnet/backend:latest
    build:
      context: .
    ports:
      - 6001:80
    environment:
      DatabaseOptions__ConnectionString: "User ID=postgres;Password=changeme;Host=postgres;Port=5432;Database=postgres;"
      SwaggerOptions__ApplicationName: "Todos API Docker"
      LoggingOptions__ApplicationName: "Todos API Docker"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "changeme"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:changeme@postgres:5432/postgres?sslmode=disable"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./volumes/prometheus/:/prometheus
      - ./prometheus/data/:/etc/prometheus/
    ports:
      - "9090:9090"
