version: "3.7"

services:
  backend:
    image: dotnet/backend:latest
    build:
      context: .
    ports:
      - 6001:80
    environment:
      DatabaseOptions__ConnectionString: "User ID=postgres;Password=changeme;Host=postgres;Port=5432;Database=postgres;"
      SwaggerOptions__ApplicationName: "Todos API Docker"
      LoggingOptions__ApplicationName: "Todos API Docker"
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "changeme"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
